USE [master]
GO

/****** Login [NYMINT\DBAMonitor]  ******/
CREATE LOGIN [NYMINT\DBAMonitor] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NYMINT\DBAMonitor]
GO

CREATE LOGIN [XRAY\DBAMonitor] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [XRAY\DBAMonitor]
GO
/****** Login [NYMINT\DBA.Group]  ******/

--CREATE LOGIN [NYMINT\DBA.Group] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--ALTER SERVER ROLE [sysadmin] ADD MEMBER [NYMINT\DBA.Group]
--GO
/****** Login [NYMINT\DBA Team]  ******/
CREATE LOGIN [NYMINT\DBA Team] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NYMINT\DBA Team]
GO
